#include "MAPL_Generic.h"
#undef RTTOV

! GEOS_SatsimGridCompMod drives the COSP satellite simulators (ISCCP, MODIS,
! MISR, CloudSat radar, CALIPSO lidar) from grid-mean cloud and
! thermodynamic fields imported from the model.
module GEOS_SatsimGridCompMod

#define USE_MAPL_UNDEF

   use ESMF
   use MAPL
   use GEOS_UtilsMod

   use gettau

   use MOD_COSP_TYPES
   use MOD_COSP, only: COSP
   !  use MOD_COSP_Modis_Simulator, only: cosp_modis
   use MOD_COSP_Modis_Simulator

   implicit none
   private

   public SetServices

   character(*), parameter :: PRIVATE_STATE = "SatSim_state"

   ! Private State
   type SatSim_State
      private

      integer :: nmask_vars = 0 ! number of masked variables
      character(len=ESMF_MAXSTR), pointer :: export_name(:) => null()
      character(len=ESMF_MAXSTR), pointer :: mask_name(:) => null()
      character(len=ESMF_MAXSTR), pointer :: newvar_name(:) => null()
      logical, pointer :: newvar(:) => null()

   end type SatSim_State

contains

   subroutine SetServices(gc, rc)
      type(ESMF_GridComp) :: gc ! gridded component
      integer, intent(out) :: rc ! return code

      integer :: status

      ! Local derived type aliases

      type(MAPL_MetaComp), pointer :: STATE
      type(ESMF_Config) :: CF

      integer :: DIMS(3)

      ! Local derived type aliases
      type(SatSim_State), pointer :: self => null() ! internal, that is

      integer :: nLines, nCols, m, vindex
      character(len=ESMF_MAXSTR) :: tmpname
      character(len=ESMF_MAXSTR) :: long_name
      character(len=ESMF_MAXSTR) :: units
      integer :: mapl_dims, vlocation
      integer, pointer :: ungridded_dims(:) => null()
      type(MAPL_UngriddedDim) :: ungrd_7, ungrd_parasol_nrefl
      character(len=ESMF_MAXSTR) :: exportName(1)
      type(MAPL_VarSpec), pointer :: ExportSpec(:) => null()
      logical :: found

      ! Attach the internal state to the GC as a named private state
      _SET_NAMED_PRIVATE_STATE(gc, SatSim_State, PRIVATE_STATE)
      _GET_NAMED_PRIVATE_STATE(gc, SatSim_State, PRIVATE_STATE, self)

      ! Set entry points (Finalize uses the MAPL generic default)
      call MAPL_GridCompSetEntryPoint(gc, ESMF_METHOD_INITIALIZE, Initialize, _RC)
      call MAPL_GridCompSetEntryPoint(gc, ESMF_METHOD_RUN, Run, phase_name="run", _RC)

      ! Get the configuration from the component
      call ESMF_GridCompGet(gc, CONFIG=CF, _RC)

      ! Import and export specs are generated by the MAPL ACG from
      ! Satsim_StateSpecs.rc. The ungridded-dimension descriptors referenced
      ! there must be set before the includes. ungrd_7 is the 7-bin histogram
      ! axis shared by the ISCCP, CFAD and MISR stacked exports.
      ungrd_7 = MAPL_UngriddedDim(7, name='bins7', units='1')
      ungrd_parasol_nrefl = MAPL_UngriddedDim(PARASOL_NREFL, name='parasol_nrefl', units='1')

#include "Satsim_Import___.h"
#include "Satsim_Export___.h"

      ! SATORB is a FieldBundle import; the ACG only supports fields, so it is
      ! added by hand. Must mirror the ORBIT component's export spec in
      ! MAPL_OrbGridCompMod.F90.
      call MAPL_GridCompAddSpec(gc, &
           state_intent=ESMF_STATEINTENT_IMPORT, &
           short_name='SATORB', &
           standard_name='Satellite_orbits', &
           dims="xy", &
           vertical_stagger=MAPL_VERTICAL_STAGGER_NONE, &
           units='days', &
           itemtype=MAPL_STATEITEM_FIELDBUNDLE, _RC)

      ! parse resource file for masks
      CF = ESMF_ConfigCreate(_RC)
      inquire(file='SatSim.rc', exist=found)
      if (found) then
         call ESMF_ConfigLoadFile(CF, 'SatSim.rc', _RC)
         call ESMF_ConfigGetDim(CF, nLines, nCols, LABEL='Masked_Exports::', rc=status)
         if (status == ESMF_SUCCESS) then
            self%nmask_vars = nLines
            allocate(self%export_name(nLines), self%mask_name(nLines), self%newvar_name(nLines), self%newvar(nLines), &
                 _STAT)
            call ESMF_ConfigFindLabel(CF, 'Masked_Exports::', _RC)
            do m = 1, nLines
               call ESMF_ConfigNextLine(CF, _RC)
               call ESMF_ConfigGetAttribute(CF, self%export_name(m), _RC)
               call ESMF_ConfigGetAttribute(CF, self%mask_name(m), _RC)
               call ESMF_ConfigGetAttribute(CF, tmpname, rc=status)
               if (status == ESMF_SUCCESS) then
                  self%newvar_name(m) = tmpname
                  self%newvar(m) = .true.
               else
                  self%newvar_name(m) = self%export_name(m)
                  self%newvar(m) = .false.
               end if
            end do
         end if
      else
         self%nmask_vars = 0
      end if
      if (MAPL_AM_I_Root()) then
         write(*, *)'Parsing of satsim.rc'
         do m = 1, self%nmask_vars
            write(*, *)m, self%newvar(m)
            write(*, *)trim(self%export_name(m)), ' ', trim(self%mask_name(m)), ' ', trim(self%newvar_name(m))
         end do
      end if

      call MAPL_GetObjectFromGC(gc, STATE, _RC)

      do m = 1, self%nmask_vars
         if (self%newvar(m)) then
            call MAPL_Get(STATE, ExportSpec=ExportSpec, _RC)
            vindex = MAPL_VarSpecGetIndex(ExportSpec, self%export_name(m), _RC)
            call MAPL_VarSpecGet(ExportSpec(vindex), long_name=long_name, &
                 units=units, DIMS=mapl_dims, vlocation=vlocation, ungridded_dims=ungridded_dims, _RC)
            if (associated(ungridded_dims)) then
               call MAPL_AddExportSpec(gc, &
                    SHORT_NAME=self%newvar_name(m), &
                    long_name=long_name, &
                    units=units, &
                    ungridded_dims=ungridded_dims, &
                    DIMS=mapl_dims, &
                    vlocation=vlocation, _RC)
               nullify(ungridded_dims)
            else
               call MAPL_AddExportSpec(gc, &
                    SHORT_NAME=self%newvar_name(m), &
                    long_name=long_name, &
                    units=units, &
                    DIMS=mapl_dims, &
                    vlocation=vlocation, _RC)
            end if
            exportName(1) = self%newvar_name(m)
            call MAPL_DoNotDeferExport(gc, exportName, _RC)
         end if
         call MAPL_DoNotDeferExport(gc, self%export_name, _RC)
      end do

      _RETURN(_SUCCESS)

   end subroutine SetServices

   subroutine Initialize(gc, import, export, clock, rc)
      type(ESMF_GridComp) :: gc ! Gridded component
      type(ESMF_State) :: import ! Import state
      type(ESMF_State) :: export ! Export state
      type(ESMF_Clock) :: clock ! The clock
      integer, intent(out) :: rc ! Error code

      ! Creates the alarm that gates how often Run() calls the COSP simulators,
      ! with ring interval set by SATSIM_DT (seconds). Run() retrieves it from
      ! the clock by name. MAPL2 got this for free from the generic RUNALARM.

      integer :: status
      integer :: satsim_dt
      real :: run_dt
      type(ESMF_TimeInterval) :: satsim_alarm_interval, time_step
      type(ESMF_Time) :: current_time, ring_time
      type(ESMF_Calendar) :: cal
      integer :: yy, mm, dd, reference_date, reference_time
      logical :: run_at_interval_start
      type(ESMF_Alarm) :: satsim_alarm

      call MAPL_ClockGet(clock, dt=run_dt, _RC)
      call MAPL_GridCompGetResource(gc, "SATSIM_DT", satsim_dt, default=nint(run_dt), _RC)
      ! same checks as MAPL2's handle_clock_and_main_alarm; a zero interval would hang the ring_time loop below
      _ASSERT(satsim_dt > 0, "SATSIM_DT must be a positive number of seconds")
      _ASSERT(mod(satsim_dt, nint(run_dt)) == 0, "SATSIM_DT must be a multiple of the clock time step")
      call ESMF_TimeIntervalSet(satsim_alarm_interval, s=satsim_dt, _RC)

      ! Alarm set up as in MAPL2's handle_clock_and_main_alarm (MAPL_Generic.F90),
      ! which MAPL3 no longer provides for components
      call ESMF_ClockGet(clock, currTime=current_time, timeStep=time_step, calendar=cal, _RC)
      call ESMF_TimeGet(current_time, yy=yy, mm=mm, dd=dd, _RC)
      call MAPL_GridCompGetResource(gc, "RUN_AT_INTERVAL_START", run_at_interval_start, default=.false., _RC)
      ! alarm reference date and time default to midnight of the current day
      call MAPL_GridCompGetResource(gc, "REFERENCE_DATE", reference_date, default=yy * 10000 + mm * 100 + dd, _RC)
      call MAPL_GridCompGetResource(gc, "REFERENCE_TIME", reference_time, default=0, _RC)
      call ESMF_TimeSet(ring_time, &
           yy=reference_date / 10000, mm=mod(reference_date, 10000) / 100, dd=mod(reference_date, 100), &
           h=reference_time / 10000, m=mod(reference_time, 10000) / 100, s=mod(reference_time, 100), &
           calendar=cal, _RC)
      if (ring_time > current_time) then
         ring_time = ring_time - (int((ring_time - current_time) / satsim_alarm_interval) + 1) * satsim_alarm_interval
      end if
      ! back off by the clock's dt since the clock advances AFTER the run method
      if (.not. run_at_interval_start) ring_time = ring_time - time_step
      ! make sure that ring_time is not in the past
      do while (ring_time < current_time)
         ring_time = ring_time + satsim_alarm_interval
      end do

      satsim_alarm = ESMF_AlarmCreate( &
           name="satsim_alarm", &
           clock=clock, &
           ringTime=ring_time, &
           ringInterval=satsim_alarm_interval, &
           sticky=.false., _RC)
      if (ring_time == current_time) then
         call ESMF_AlarmRingerOn(satsim_alarm, _RC)
      end if

      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(import)
      _UNUSED_DUMMY(export)
   end subroutine Initialize

   subroutine Run(gc, import, export, clock, rc)
      type(ESMF_GridComp) :: gc ! Gridded component
      type(ESMF_State) :: import ! Import state
      type(ESMF_State) :: export ! Export state
      type(ESMF_Clock) :: clock ! The clock
      integer, intent(out) :: rc ! Error code

      integer :: status

      ! Local derived type aliases
      type(ESMF_Grid) :: esmfgrid
      type(ESMF_Alarm) :: satsim_alarm

      ! Local variables
      integer :: IM, JM, LM

      ! Pointers to imports and exports (generated by the MAPL ACG from
      ! Satsim_StateSpecs.rc; also host-associated into SIM_DRIVER)
#include "Satsim_DeclarePointer___.h"

      ! Get the component's grid dimensions.
      call MAPL_GridCompGet(gc, grid=esmfgrid, num_levels=LM, _RC)
      call MAPL_GridGet(esmfgrid, IM=IM, JM=JM, _RC)

      ! Retrieve the alarm (created once in Initialize) that gates how often
      ! the COSP simulators are run below.
      call ESMF_ClockGetAlarm(clock, alarmname="satsim_alarm", alarm=satsim_alarm, _RC)

      if (.not. ESMF_AlarmIsRinging(satsim_alarm)) then
         _RETURN(_SUCCESS)
      end if

      call MAPL_GridCompTimerStart(gc, "DRIVER", _RC)

      call SIM_DRIVER(IM, JM, LM, _RC)

      call MAPL_GridCompTimerStop(gc, "DRIVER", _RC)

      _RETURN(_SUCCESS)

   contains

      subroutine SIM_DRIVER(IM, JM, LM, rc)
         integer, intent(in) :: IM, JM, LM
         integer, optional, intent(out) :: rc

         !  Locals

         character(len=ESMF_MAXSTR) :: name
         integer :: status

         ! Import pointers (T, PLE, ZLE, QV, FCLD, RDF*, Q*TOT, MCOSZ, FRLAND,
         ! TS, FROCEAN) are host-associated from Run. PLE and ZLE are indexed 0:LM.

         ! These are the same, in logical 2 dimensions for icarus's sake
         real, dimension(IM * JM, 0:LM) :: ZLE2D
         real, dimension(IM * JM) :: MCOSZCOSP, FRLANDCOSP, TSCOSP, FROCEANCOSP

         ! These are the same, converted to upside-down and 2d
         real, dimension(IM * JM, LM) :: TCOSP, PLOCOSP, QVCOSP, FCLDCOSP
         real, dimension(IM * JM, LM) :: RDFLCOSP, RDFICOSP
         real, dimension(IM * JM, LM) :: QLTOTCOSP, QITOTCOSP
         real, dimension(IM * JM, LM) :: QRTOTCOSP, QSTOTCOSP, QGTOTCOSP
         real, dimension(IM * JM, LM) :: RDFRCOSP, RDFSCOSP, RDFGCOSP
         real, dimension(IM * JM, 0:LM) :: PLECOSP, PLE2DTOA0INV, ZLECOSP

         ! Local variables needed for all simulators
         real, dimension(IM, JM, LM) :: PLO, RH, QST
         real, dimension(IM * JM, LM) :: RHCOSP
         integer :: Npoints
         real, dimension(:, :, :), target, allocatable :: frac_out
         real, dimension(IM * JM, LM) :: frac_ls
         integer :: isccp_overlap
         integer :: i, j, k, l, icb, ict
         integer :: scops_debug = 0
         integer :: idebug = 0
         integer :: idebugcol = 0
         real, dimension(:, :), pointer :: column_frac_out

         !  The follwing assignments are for variables needed for COSP
         integer :: melt_lay ! melting layer model off=0, on=1
         integer :: Naero ! Number of aerosol species
         integer :: surface_radar ! surface=1,spaceborne=0
         ! Time [days] - need to do something about this - afe
         double precision :: time = 1.D0
         double precision :: time_bands(2, 1) = 1.D0

         ! COSP types
         type(cosp_config) :: cfg ! Configuration options
         type(cosp_gridbox) :: gbx ! Gridbox information. Input for COSP
         type(cosp_subgrid) :: sgx ! Subgrid outputs
         type(cosp_sgradar) :: sgradar ! Output from radar simulator
         type(cosp_sglidar) :: sglidar ! Output from lidar simulator
         type(cosp_isccp) :: isccp ! Output from ISCCP simulator
         type(cosp_vgrid) :: vgrid ! Information on vertical grid of stats
         type(cosp_radarstats) :: stradar ! Summary statistics from radar simulator
         type(cosp_lidarstats) :: stlidar ! Summary statistics from lidar simulator
         type(cosp_modis) :: modis ! Output from MODIS simulator
         type(cosp_misr) :: misr ! Output from MISR simulator

         ! RRTOV paramters needed only by COSP, otherwise unused
         integer :: Npoints_it
         logical :: use_precipitation_fluxes, use_reff
         integer :: Plat
         integer :: Sat
         integer :: Inst
         integer :: Nchan
         integer :: Ichan(0)
         real :: SurfEm(0)
         real :: ZenAng
         real :: co2, ch4, n2o, co

         !  The follwing definitions are for variables needed for COSP and isccp/icarus
         real :: CCA(IM, JM, LM) ! convective clouds fraction, goes into scops
         real :: CCACOSP(IM * JM, LM) ! convective clouds fraction, goes into scops
         real :: DTAU_S(IM, JM, LM)
         real :: dtau_sCOSP(IM * JM, LM)
         real, dimension(IM, JM, LM, 4) :: CWC, REFF
         real, dimension(IM, JM, LM, 4) :: tausw, taulw
         real, dimension(LM, 4) :: dumtaubeam
         real, dimension(LM) :: dumasycl
         real, dimension(0:LM) :: dumtcldlyr
         real, dimension(0:LM) :: dumenn
         real :: taucir
         real, dimension(IM, JM, LM, 10) :: TAUDIAG
         real :: sunlit(IM * JM)
         real, dimension(IM, JM, LM) :: DELP, TAUSWICE, TAUSWLIQ, EMISS
         real, dimension(IM * JM, LM) :: EMISS2D, EMISSCOSP
         real :: isccp_emsfc_lw
         integer :: isccp_top_height
         integer :: isccp_top_height_direction

         ! icarus/isccp outputs
         real, dimension(IM * JM) :: ISCCP_totalcldarea
         real, dimension(IM * JM) :: ISCCP_meanptop
         real, dimension(IM * JM, 7, 7) :: fq_isccp
         real, dimension(IM, JM, 7, 7) :: fq_isccp3D
         real, dimension(IM * JM) :: ISCCP_meanalbedocld
         real, dimension(IM * JM) :: ISCCP_meanallskybrighttemp

         ! variables for lidar simulator
         real, dimension(IM * JM, LM) :: lidar_pmol
         real, dimension(:, :, :), allocatable :: lidar_beta_tot, lidar_tau_tot
         real, dimension(IM * JM, PARASOL_NREFL) :: REFL

         ! variables for lidar and radar simulators
         real, dimension(IM * JM, LM) :: ZLOCOSP
         real, dimension(IM * JM, LM) :: ZLO2D
         real :: K2
         integer :: use_mie_tables ! use a precomputed lookup table? yes=1,no=0,2=use first
         !  column everywhere
         integer :: use_gas_abs ! include gaseous absorption? yes=1,no=0
         integer :: do_ray ! calculate/output Rayleigh refl=1, not=0
         integer :: Nprmts_max_hydro ! Max number of parameters for hydrometeor size distributions
         integer :: Nprmts_max_aero ! Max number of parameters for aerosol size distributions
         real :: radar_freq
         integer :: lidar_ice_type !Ice particle shape in lidar calculations
         ! (0=ice-spheres;1=ice-non-spherical)

         ! radar and lidar simulator output -- the admittedly confusing lidar_ and radar_
         ! suffixes indicate the cosp return structures that the variables are copied out of
         real, dimension(:, :, :), allocatable :: radar_ze_tot
         real, dimension(:, :, :), allocatable :: radar_ze_tot_tmp
         logical, dimension(:, :, :), allocatable :: radar_ze_tot_mask
         integer, dimension(IM * JM, LM) :: ncvalid
         real, dimension(IM * JM, LM) :: radar_ze_tot_max
         real, dimension(IM * JM, LM) :: radar_ze_tot_mean

         real, dimension(IM * JM, dBZe_bins, LM) :: radar_cfad_ze
         real, dimension(IM * JM, LM) :: radar_lidar_only_freq_cloud
         real, dimension(IM * JM) :: radar_lidar_tcc
         real, dimension(IM * JM) :: land_mask

         real, dimension(IM * JM, SR_BINS, LM) :: lidar_cfad_sr ! CFAD of scattering ratio
         real, dimension(IM * JM, LM) :: lidar_lidarcld ! 3D "lidar" cloud fraction
         real, dimension(IM * JM, LIDAR_NCAT) :: lidar_cldlayer ! low, mid, high-level lidar cloud cover
         real, dimension(IM * JM, PARASOL_NREFL) :: lidar_parasolrefl ! mean parasol reflectance

         real, dimension(IM * JM, 7, MISR_N_CTH) :: fq_MISR
         real, dimension(IM * JM, MISR_N_CTH) :: MISR_dist_model_layertops
         real, dimension(IM * JM) :: MISR_meanztop
         real, dimension(IM * JM) :: MISR_cldarea

         real, dimension(IM * JM) :: MODIS_Cloud_Fraction_Total_Mean
         real, dimension(IM * JM) :: MODIS_Cloud_Fraction_Water_Mean
         real, dimension(IM * JM) :: MODIS_Cloud_Fraction_Ice_Mean
         real, dimension(IM * JM) :: MODIS_Cloud_Fraction_High_Mean
         real, dimension(IM * JM) :: MODIS_Cloud_Fraction_Mid_Mean
         real, dimension(IM * JM) :: MODIS_Cloud_Fraction_Low_Mean
         real, dimension(IM * JM) :: MODIS_Optical_Thickness_Total_Mean
         real, dimension(IM * JM) :: MODIS_Optical_Thickness_Water_Mean
         real, dimension(IM * JM) :: MODIS_Optical_Thickness_Ice_Mean
         real, dimension(IM * JM) :: MODIS_Optical_Thickness_Total_LogMean
         real, dimension(IM * JM) :: MODIS_Optical_Thickness_Water_LogMean
         real, dimension(IM * JM) :: MODIS_Optical_Thickness_Ice_LogMean
         real, dimension(IM * JM) :: MODIS_Cloud_Particle_Size_Water_Mean
         real, dimension(IM * JM) :: MODIS_Cloud_Particle_Size_Ice_Mean
         real, dimension(IM * JM) :: MODIS_Cloud_Top_Pressure_Total_Mean
         real, dimension(IM * JM) :: MODIS_Liquid_Water_Path_Mean
         real, dimension(IM * JM) :: MODIS_Ice_Water_Path_Mean
         real, dimension(IM * JM, 7, 7) :: MODIS_Optical_Thickness_vs_Cloud_Top_Pressure

         integer :: BEGSEG, ENDSEG

         type(SatSim_State), pointer :: self => null()
         type(MAPL_MetaComp), pointer :: STATE
         integer :: mapl_dims, vindex
         integer, pointer :: ungridded_dims(:)
         type(MAPL_VarSpec), pointer :: ExportSpec(:)
         real, pointer, dimension(:, :) :: ptr2d, ptr2d_new
         real, pointer, dimension(:, :) :: ptr_mask
         real, pointer, dimension(:, :, :) :: ptr3d, ptr3d_new
         type(ESMF_FieldBundle) :: bundle

         integer :: use_satsim, use_satsim_isccp, use_satsim_modis, use_satsim_lidar, use_satsim_radar, use_satsim_misr
         integer :: ncolumns

         integer, allocatable :: Gdims(:)
         integer :: IM_World, JM_World, imsize

         call MAPL_GridCompGetResource(gc, "USE_SATSIM", use_satsim, default=0, _RC)
         call MAPL_GridCompGetResource(gc, "USE_SATSIM_ISCCP", use_satsim_isccp, default=0, _RC)
         call MAPL_GridCompGetResource(gc, "USE_SATSIM_MODIS", use_satsim_modis, default=0, _RC)
         call MAPL_GridCompGetResource(gc, "USE_SATSIM_RADAR", use_satsim_radar, default=0, _RC)
         call MAPL_GridCompGetResource(gc, "USE_SATSIM_LIDAR", use_satsim_lidar, default=0, _RC)
         call MAPL_GridCompGetResource(gc, "USE_SATSIM_MISR", use_satsim_misr, default=0, _RC)

         ! imsize is the equivalent number of longitudes, used only to pick the
         ! default subcolumn count. MAPL2 string-parsed AGCM_GRIDNAME for this;
         ! take it from the grid instead (cubed-sphere has JM_World = 6*IM_World).
         ! esmfgrid is host-associated from Run.
         call MAPL_GridGetGlobalCellCountPerDim(esmfgrid, globalCellCountPerDim=Gdims, _RC)
         IM_World = Gdims(1)
         JM_World = Gdims(2)
         if (JM_World == 6 * IM_World) then
            imsize = 4 * IM_World
         else
            imsize = IM_World
         end if
         associate(default_Ncolumns => min(30, max(1, int(4 * 5760 * 4 / imsize))))
            call MAPL_GridCompGetResource(gc, "SATSIM_NCOLUMNS", ncolumns, default=default_Ncolumns, _RC)
         end associate

         call MAPL_GridCompGetResource(gc, "SATSIM_POINTS_PER_ITERATION", Npoints_it, default=-999, _RC)

         allocate(frac_out(IM * JM, ncolumns, LM), _STAT)
         allocate(lidar_beta_tot(IM * JM, ncolumns, LM), _STAT)
         allocate(lidar_tau_tot(IM * JM, ncolumns, LM), _STAT)
         allocate(radar_ze_tot(IM * JM, ncolumns, LM), _STAT)
         allocate(radar_ze_tot_tmp(IM * JM, ncolumns, LM), _STAT)
         allocate(radar_ze_tot_mask(IM * JM, ncolumns, LM), _STAT)

         ! Pointers to imports and exports
#include "Satsim_GetPointer___.h"

         !  The follwing assignments are for variables needed for COSP and isccp/icarus
         isccp_top_height = 1 !  1 = adjust top height using both a computed
         isccp_top_height_direction = 2 ! direction for finding atmosphere pressure level
         isccp_emsfc_lw = 0.999
         sunlit = 0.0
         icb = 58
         ict = 48

         ! anything that needs to be calculated in 3D is done so, to
         ! be converted to 2D and inverted later
         PLO = 0.5 * (PLE(:, :, 1:LM) + PLE(:, :, 0:LM - 1))

         ! The following are convective terms, which we don't want now
         CCA = 0.0

         ! the following is in lieu of
         !      where(FCLD.gt.0.)
         ! to avoid stupid high cwc, which makes for stupid high dtau_s, which
         ! crashes icarus
         where (FCLD > 0.01)
            CWC(:, :, :, 1) = max(QITOT / FCLD, 1.0e-12)
            CWC(:, :, :, 2) = max(QLTOT / FCLD, 1.0e-12)
            CWC(:, :, :, 3) = max(QRTOT / FCLD, 1.0e-12)
            CWC(:, :, :, 4) = max(QSTOT / FCLD, 1.0e-12)
            elsewhere
            CWC(:, :, :, 1) = 0.
            CWC(:, :, :, 2) = 0.
            CWC(:, :, :, 3) = 0.
            CWC(:, :, :, 4) = 0.
         end where

         ! delp in Pascals, reff in microns

#ifdef USE_MAPL_UNDEF
         where (RDFI == MAPL_UNDEF)
            RDFI = 36.e-6
         end where
         where (RDFL == MAPL_UNDEF)
            RDFL = 14.e-6
         end where
         where (RDFR == MAPL_UNDEF)
            RDFR = 50.e-6
         end where
         where (RDFS == MAPL_UNDEF)
            RDFS = 50.e-6
         end where
         where (RDFG == MAPL_UNDEF)
            RDFG = 50.e-6
         end where
#endif

         REFF(:, :, :, 1) = RDFI * 1.e6
         REFF(:, :, :, 2) = RDFL * 1.e6
         REFF(:, :, :, 3) = RDFR * 1.e6
         REFF(:, :, :, 4) = RDFS * 1.e6

         DELP = PLE(:, :, 1:LM) - PLE(:, :, 0:LM - 1)

         do i = 1, IM
            do j = 1, JM

               ! NOTE: mcosz is being passed in but not used since we aren't doing cloud scaling
               !       as the 0's at the end of inputs determine. If scaling is needed, mcosz might
               !       be the wrong cosine to use (i.e., not the mean). Also, dummies will need to
               !       be replaced if needed.
               call getvistau(LM, MCOSZ(i, j), DELP(i, j, :), FCLD(i, j, :), REFF(i, j, :, :), CWC(i, j, :, :), 0, 0,&
                    dumtaubeam(:, :), tausw(i, j, :, :), dumasycl(:))

               ! IR Taus: Here we calculate band 4 only. Again, dummies for unneeded arrays.
               call getirtau(4, LM, DELP(i, j, :), FCLD(i, j, :), REFF(i, j, :, :), CWC(i, j, :, :),&
                    taulw(i, j, :, :), dumtcldlyr(:), dumenn(:))

               do k = 1, LM

                  ! NOTE: If you wish to include both falling rain and falling snow to
                  !       DTAU_S and EMISS, use the lines below with all four
                  !       tausw and taulw returns

                  ! VIS
                  ! ---

                  !DTAU_S(i,j,k) = tausw(i,j,k,1)+tausw(i,j,k,2)+tausw(i,j,k,3)+tausw(i,j,k,4)
                  DTAU_S(i, j, k) = tausw(i, j, k, 1) + tausw(i, j, k, 2)

                  ! IR
                  ! --

                  !taucir = taulw(i,j,k,1) + taulw(i,j,k,2) + taulw(i,j,k,3) + taulw(i,j,k,4)
                  taucir = taulw(i, j, k, 1) + taulw(i, j, k, 2)

                  EMISS(i, j, k) = 1 - exp(-1.0 * taucir)

               end do

            end do
         end do

         !  The follwing assignments are for variables needed for all simulators
         Npoints = IM * JM
         isccp_overlap = 3 !  overlap type: 1=max, 2=rand, 3=max/rand
         ! used by SCOPS, COSP and icarus

         !  The follwing assignments are for variables needed for COSP
         Naero = 1 ! Number of aerosol species (Not used)
         if (Npoints_it == -999) Npoints_it = Npoints ! Number of gridpoints processed in one iteration (probably not used)
         use_precipitation_fluxes = .false.
         use_reff = .true.
         surface_radar = 0 ! surface=1, spaceborne=0
         melt_lay = 0 ! melting layer model off=0, on=1
         time = 0 ! Time since start of run [days] - something should be done about this

         ! Switches in cfg need to be toggled to make things run right

         ! remember these are integers so + is logical or, not and

         if (use_satsim + use_satsim_isccp + use_satsim_modis > 0) then ! isccp needed for modis
            cfg%Lisccp_sim = .true.
         else
            cfg%Lisccp_sim = .false.
         end if

         if (use_satsim + use_satsim_modis > 0) then
            cfg%Lmodis_sim = .true.
         else
            cfg%Lmodis_sim = .false.
         end if

         if (use_satsim + use_satsim_radar > 0) then
            cfg%Lradar_sim = .true.
         else
            cfg%Lradar_sim = .false.
         end if

         if (use_satsim + use_satsim_lidar > 0) then
            cfg%Llidar_sim = .true.
            cfg%LCFADLIDARSR532 = .true.
         else
            cfg%Llidar_sim = .false.
            cfg%LCFADLIDARSR532 = .false.
         end if

         if (use_satsim + use_satsim_misr > 0) then
            cfg%Lmisr_sim = .true.
         else
            cfg%Lmisr_sim = .false.
         end if

         if (use_satsim /= 0 .or. (use_satsim_lidar + use_satsim_radar == 2)) then
            cfg%Lstats = .true.
         else
            cfg%Lstats = .false.
         end if

         ! RRTOV paramters (not used)
         Plat = 0
         Sat = 0
         Inst = 0
         Nchan = 0
         ZenAng = 0.0
         Ichan = 0
         SurfEm = 0.0
         co2 = 0.0
         ch4 = 0.0
         n2o = 0.0
         co = 0.0

         !  The follwing assignments are for variables needed for COSP and lidar_simulator
         lidar_ice_type = 0 ! Ice particle shape in lidar calculations (0=ice-spheres ; 1=ice-non-spherical)

         !  The follwing assignments are for variables needed for COSP and radar_simulator
         Nprmts_max_aero = 1 ! Max number of parameters for aerosol size distributions (Not used)
         Nprmts_max_hydro = 12 ! Max number of parameters for hydrometeor size distributions
         radar_freq = 94.0 ! CloudSat radar frequency (GHz)
         K2 = -1. ! |K|^2, -1=use frequency dependent default
         do_ray = 0 ! calculate/output Rayleigh refl=1, not=0
         use_gas_abs = 1 ! include gaseous absorption? yes=1,no=0
         use_mie_tables = 0 ! use a precomputed lookup table? yes=1,no=0
         QST = GEOS_QSAT(T, PLO / 100.)
         RH = (QV / QST) * 100.0 ! rel. humidity (in percent)
         land_mask = 0.0 !  needed for stats -- should be changed [0 - Ocean, 1 - Land]

         RHCOSP = reshape(RH(:, :, LM:1:-1), (/ IM * JM, LM /))
         PLOCOSP = reshape(PLO(:, :, LM:1:-1), (/ IM * JM, LM /))
         QVCOSP = reshape(QV(:, :, LM:1:-1), (/ IM * JM, LM /))
         CCACOSP = reshape(CCA(:, :, LM:1:-1), (/ IM * JM, LM /))
         dtau_sCOSP = reshape(DTAU_S(:, :, LM:1:-1), (/ IM * JM, LM /))
         TCOSP = reshape(T(:, :, LM:1:-1), (/ IM * JM, LM /))
         EMISSCOSP = reshape(EMISS(:, :, LM:1:-1), (/ IM * JM, LM /))
         FCLDCOSP = reshape(FCLD(:, :, LM:1:-1), (/ IM * JM, LM /))
         RDFLCOSP = reshape(RDFL(:, :, LM:1:-1), (/ IM * JM, LM /))
         RDFICOSP = reshape(RDFI(:, :, LM:1:-1), (/ IM * JM, LM /))
         RDFRCOSP = reshape(RDFR(:, :, LM:1:-1), (/ IM * JM, LM /))
         RDFSCOSP = reshape(RDFS(:, :, LM:1:-1), (/ IM * JM, LM /))
         RDFGCOSP = reshape(RDFG(:, :, LM:1:-1), (/ IM * JM, LM /))
         QLTOTCOSP = reshape(QLTOT(:, :, LM:1:-1), (/ IM * JM, LM /))
         QITOTCOSP = reshape(QITOT(:, :, LM:1:-1), (/ IM * JM, LM /))
         QRTOTCOSP = reshape(QRTOT(:, :, LM:1:-1), (/ IM * JM, LM /))
         QSTOTCOSP = reshape(QSTOT(:, :, LM:1:-1), (/ IM * JM, LM /))
         QGTOTCOSP = reshape(QGTOT(:, :, LM:1:-1), (/ IM * JM, LM /))
         PLECOSP = reshape(PLE(:, :, LM:0:-1), (/ IM * JM, LM + 1 /))
         MCOSZCOSP = reshape(MCOSZ, (/ IM * JM /))
         FRLANDCOSP = reshape(FRLAND, (/ IM * JM /))
         FROCEANCOSP = reshape(FROCEAN, (/ IM * JM /))
         TSCOSP = reshape(TS, (/ IM * JM /))

         ZLE2D = reshape(ZLE, (/ IM * JM, LM + 1 /))
         do k = 0, LM
            ZLE2D(:, k) = ZLE2D(:, k) - ZLE2D(:, LM)
         end do
         ZLECOSP = ZLE2D(:, LM:0:-1)
         ZLO2D = 0.5 * (ZLE2D(:, 0:LM - 1) + ZLE2D(:, 1:LM))
         ZLOCOSP = ZLO2D(:, LM:1:-1)

         where (MCOSZCOSP > 0.0) sunlit = 1.0
         where (FROCEANCOSP < 0.5) land_mask = 1.0

         ! zero out exports
         ISCCP_totalcldarea = 0.0
         ISCCP_meanptop = 0.0
         ISCCP_meanalbedocld = 0.0
         ISCCP_meanallskybrighttemp = 0.0
         frac_out = 0.0
         fq_isccp = 0.0
         lidar_lidarcld = 0.0
         lidar_cldlayer = 0.0
         lidar_parasolrefl = 0.0
         lidar_cfad_sr = 0.0
         radar_lidar_tcc = 0.0
         radar_lidar_only_freq_cloud = 0.0
         radar_cfad_ze = 0.0
         radar_ze_tot = 0.0

         lidar_pmol = 0.0
         REFL = 0.0

         call construct_cosp_gridbox(time &
              , time_bands &
              , radar_freq &
              , surface_radar &
              , use_mie_tables &
              , use_gas_abs &
              , do_ray &
              , melt_lay &
              , K2 &
              , Npoints &
              , LM &
              , ncolumns &
              , N_HYDRO &
              , Nprmts_max_hydro &
              , Naero &
              , Nprmts_max_aero &
              , Npoints_it &
              , lidar_ice_type &
              , isccp_top_height &
              , isccp_top_height_direction &
              , isccp_overlap &
              , isccp_emsfc_lw &
              , use_precipitation_fluxes &
              , use_reff &
              , Plat &
              , Sat &
              , Inst &
              , Nchan &
              , ZenAng &
              , Ichan &
              , SurfEm &
              , co2 &
              , ch4 &
              , n2o &
              , co &
              , gbx)

         call construct_cosp_subgrid(Npoints, ncolumns, LM, sgx)
         if (cfg%Lisccp_sim) call construct_cosp_isccp(cfg, Npoints, ncolumns, LM, isccp)
         if (cfg%Lradar_sim) call construct_cosp_sgradar(cfg, Npoints, ncolumns, LM, N_HYDRO, sgradar)
         if (cfg%Llidar_sim) call construct_cosp_sglidar(cfg, Npoints, ncolumns, LM, N_HYDRO, PARASOL_NREFL, sglidar)
         if (cfg%Lmodis_sim) call construct_cosp_modis(cfg, Npoints, modis)
         if (cfg%Lmisr_sim) call construct_cosp_misr(cfg, Npoints, misr)

         ! vgrid is use for lidar and radar simulation stats, but only if the stats are on
         ! a different grid from the model.  So mostly dummy params get passed`
         call construct_cosp_vgrid(gbx, 0, .false., .false., vgrid)

         if (cfg%Lradar_sim) call construct_cosp_radarstats(cfg, Npoints, ncolumns, LM, N_HYDRO, stradar)
         if (cfg%Llidar_sim) call construct_cosp_lidarstats(cfg, Npoints, ncolumns, LM, N_HYDRO, PARASOL_NREFL, stlidar)

         BEGSEG = 1
         ENDSEG = Npoints

         gbx%T = TCOSP(BEGSEG:ENDSEG, :)
         gbx%SH = QVCOSP(BEGSEG:ENDSEG, :)
         gbx%Q = RHCOSP(BEGSEG:ENDSEG, :)
         gbx%CCA = CCACOSP(BEGSEG:ENDSEG, :)
         gbx%TCA = FCLDCOSP(BEGSEG:ENDSEG, :)
         ! in cosp_types, gbx%ph is supposed to be half pressure levels, with the bottom as surface
         !   pressure -- see psfc in cosp_test
         gbx%ph = PLECOSP(BEGSEG:ENDSEG, 1:LM)
         gbx%p = PLOCOSP(BEGSEG:ENDSEG, :)
         gbx%psfc = PLECOSP(BEGSEG:ENDSEG, 0) ! surface pressure
         gbx%DTAU_S = dtau_sCOSP(BEGSEG:ENDSEG, :)
         gbx%dtau_c = 0.
         gbx%dem_s = EMISSCOSP(BEGSEG:ENDSEG, :)
         gbx%dem_c = 0.
         gbx%sunlit = sunlit(BEGSEG:ENDSEG)
         gbx%land = land_mask(BEGSEG:ENDSEG)
         gbx%skt = TSCOSP(BEGSEG:ENDSEG)
         gbx%mr_hydro(:, :, I_LSCLIQ) = QLTOTCOSP(BEGSEG:ENDSEG, :)
         gbx%mr_hydro(:, :, I_LSCICE) = QITOTCOSP(BEGSEG:ENDSEG, :)
         gbx%mr_hydro(:, :, I_LSRAIN) = QRTOTCOSP(BEGSEG:ENDSEG, :)
         gbx%mr_hydro(:, :, I_LSSNOW) = QSTOTCOSP(BEGSEG:ENDSEG, :)
         gbx%mr_hydro(:, :, I_LSGRPL) = QGTOTCOSP(BEGSEG:ENDSEG, :)
         gbx%mr_hydro(:, :, I_CVCLIQ) = 0.0
         gbx%mr_hydro(:, :, I_CVCICE) = 0.0
         gbx%mr_hydro(:, :, I_CVRAIN) = 0.0
         gbx%mr_hydro(:, :, I_CVSNOW) = 0.0
         gbx%REFF(:, :, I_LSCLIQ) = RDFLCOSP(BEGSEG:ENDSEG, :)
         gbx%REFF(:, :, I_LSCICE) = RDFICOSP(BEGSEG:ENDSEG, :)
         gbx%REFF(:, :, I_LSRAIN) = RDFRCOSP(BEGSEG:ENDSEG, :)
         gbx%REFF(:, :, I_LSSNOW) = RDFSCOSP(BEGSEG:ENDSEG, :)
         gbx%REFF(:, :, I_LSGRPL) = RDFGCOSP(BEGSEG:ENDSEG, :)
         gbx%zlev = ZLOCOSP(BEGSEG:ENDSEG, :)
         gbx%zlev_half = ZLECOSP(BEGSEG:ENDSEG, 1:LM)

         where (gbx%mr_hydro < 0.0) gbx%mr_hydro = 0.0

         call MAPL_GridCompTimerStart(gc, "-COSP", _RC)

         call COSP(isccp_overlap, ncolumns, cfg, vgrid, gbx, sgx, sgradar, sglidar, isccp, misr, modis, stradar, &
              stlidar)

         call MAPL_GridCompTimerStop(gc, "-COSP", _RC)

         ! Dims of sgx%frac_out (Npoints,Ncolumns,Nlevels)
         if (associated(SGFCLD)) then
            SGFCLD = reshape( &
                 sum(sgx%frac_out(:, :, LM:1:-1), 2) &
                 , (/ IM, JM, LM /)) &
                 / (1. * ncolumns)
         end if

         ! more outputs are available in the structures -- the current ones are those
         ! needed for CFMIP

         if (use_satsim_lidar + use_satsim > 0) then

            lidar_parasolrefl(BEGSEG:ENDSEG, :) = stlidar%parasolrefl
            lidar_cldlayer(BEGSEG:ENDSEG, :) = stlidar%cldlayer
            lidar_lidarcld(BEGSEG:ENDSEG, :) = stlidar%lidarcld
            lidar_cfad_sr(BEGSEG:ENDSEG, :, :) = stlidar%cfad_sr

            ! used for diagnostics
            lidar_pmol(BEGSEG:ENDSEG, :) = sglidar%beta_mol
            lidar_beta_tot(BEGSEG:ENDSEG, :, :) = sglidar%beta_tot
            lidar_tau_tot(BEGSEG:ENDSEG, :, :) = sglidar%tau_tot

         end if

         if (use_satsim_radar + use_satsim > 0) then
            radar_ze_tot(BEGSEG:ENDSEG, :, :) = sgradar%ze_tot
            radar_lidar_only_freq_cloud(BEGSEG:ENDSEG, :) = stradar%lidar_only_freq_cloud
            radar_lidar_tcc(BEGSEG:ENDSEG) = stradar%radar_lidar_tcc
            radar_cfad_ze(BEGSEG:ENDSEG, :, :) = stradar%cfad_ze
         end if

         if (use_satsim + use_satsim_isccp > 0) then
            ! cosp reverses the pressure levls of the isccp matrix for some reason
            fq_isccp(BEGSEG:ENDSEG, :, :) = isccp%fq_isccp(:, :, 7:1:-1)
            ISCCP_totalcldarea(BEGSEG:ENDSEG) = isccp%totalcldarea
            ISCCP_meanptop(BEGSEG:ENDSEG) = isccp%meanptop
            ISCCP_meanalbedocld(BEGSEG:ENDSEG) = isccp%meanalbedocld
            ISCCP_meanallskybrighttemp(BEGSEG:ENDSEG) = isccp%meantb
            fq_isccp3D = reshape(fq_isccp, (/ IM, JM, 7, 7 /))

#ifdef USE_MAPL_UNDEF

            where (fq_isccp3D < -10.0) fq_isccp3D = MAPL_UNDEF
            where (fq_isccp3D > 10.0) fq_isccp3D = MAPL_UNDEF
            where (ISCCP_totalcldarea < 0.0) ISCCP_totalcldarea = MAPL_UNDEF
            where (ISCCP_totalcldarea > 1.0) ISCCP_totalcldarea = MAPL_UNDEF
            where (ISCCP_meanptop <= 0.0) ISCCP_meanptop = MAPL_UNDEF
            where (ISCCP_meanalbedocld < 0.0) ISCCP_meanalbedocld = MAPL_UNDEF
            where (ISCCP_meanalbedocld > 1.0) ISCCP_meanalbedocld = MAPL_UNDEF
            where (ISCCP_meanallskybrighttemp < 0.0) ISCCP_meanallskybrighttemp = MAPL_UNDEF

#endif

         end if ! ( USE_SATSIM + USE_SATSIM_ISCCP > 0 )

         if (use_satsim_misr + use_satsim > 0) then
            MISR_meanztop(BEGSEG:ENDSEG) = misr%MISR_meanztop
            fq_MISR(BEGSEG:ENDSEG, :, :) = misr%fq_MISR
            MISR_cldarea(BEGSEG:ENDSEG) = misr%MISR_cldarea
            MISR_dist_model_layertops(BEGSEG:ENDSEG, :) = misr%MISR_dist_model_layertops
         end if

         if (use_satsim_modis + use_satsim > 0) then
            MODIS_Cloud_Fraction_Total_Mean(BEGSEG:ENDSEG) = modis%Cloud_Fraction_Total_Mean
            MODIS_Cloud_Fraction_Water_Mean(BEGSEG:ENDSEG) = modis%Cloud_Fraction_Water_Mean
            MODIS_Cloud_Fraction_Ice_Mean(BEGSEG:ENDSEG) = modis%Cloud_Fraction_Ice_Mean
            MODIS_Cloud_Fraction_High_Mean(BEGSEG:ENDSEG) = modis%Cloud_Fraction_High_Mean
            MODIS_Cloud_Fraction_Mid_Mean(BEGSEG:ENDSEG) = modis%Cloud_Fraction_Mid_Mean
            MODIS_Cloud_Fraction_Low_Mean(BEGSEG:ENDSEG) = modis%Cloud_Fraction_Low_Mean
            MODIS_Optical_Thickness_Total_Mean(BEGSEG:ENDSEG) = modis%Optical_Thickness_Total_Mean
            MODIS_Optical_Thickness_Water_Mean(BEGSEG:ENDSEG) = modis%Optical_Thickness_Water_Mean
            MODIS_Optical_Thickness_Ice_Mean(BEGSEG:ENDSEG) = modis%Optical_Thickness_Ice_Mean
            MODIS_Optical_Thickness_Total_LogMean(BEGSEG:ENDSEG) = modis%Optical_Thickness_Total_LogMean
            MODIS_Optical_Thickness_Water_LogMean(BEGSEG:ENDSEG) = modis%Optical_Thickness_Water_LogMean
            MODIS_Optical_Thickness_Ice_LogMean(BEGSEG:ENDSEG) = modis%Optical_Thickness_Ice_LogMean
            MODIS_Cloud_Particle_Size_Water_Mean(BEGSEG:ENDSEG) = modis%Cloud_Particle_Size_Water_Mean
            MODIS_Cloud_Particle_Size_Ice_Mean(BEGSEG:ENDSEG) = modis%Cloud_Particle_Size_Ice_Mean
            MODIS_Cloud_Top_Pressure_Total_Mean(BEGSEG:ENDSEG) = modis%Cloud_Top_Pressure_Total_Mean
            MODIS_Liquid_Water_Path_Mean(BEGSEG:ENDSEG) = modis%Liquid_Water_Path_Mean
            MODIS_Ice_Water_Path_Mean(BEGSEG:ENDSEG) = modis%Ice_Water_Path_Mean
            MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(BEGSEG:ENDSEG, :, :) = modis%&
                 Optical_Thickness_vs_Cloud_Top_Pressure
         end if

#ifdef USE_MAPL_UNDEF

         if (use_satsim_modis + use_satsim > 0) then
            ! setting to undef since 0 implies no clouds
            where (MODIS_Optical_Thickness_Total_Mean <= 0.0) MODIS_Optical_Thickness_Total_Mean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Water_Mean <= 0.0) MODIS_Optical_Thickness_Water_Mean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Ice_Mean <= 0.0) MODIS_Optical_Thickness_Ice_Mean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Total_LogMean <= 0.0) MODIS_Optical_Thickness_Total_LogMean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Water_LogMean <= 0.0) MODIS_Optical_Thickness_Water_LogMean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Ice_LogMean <= 0.0) MODIS_Optical_Thickness_Ice_LogMean = MAPL_UNDEF
            where (MODIS_Cloud_Particle_Size_Water_Mean <= 0.0) MODIS_Cloud_Particle_Size_Water_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Particle_Size_Ice_Mean <= 0.0) MODIS_Cloud_Particle_Size_Ice_Mean = MAPL_UNDEF

            where (MODIS_Cloud_Fraction_Total_Mean == R_UNDEF) MODIS_Cloud_Fraction_Total_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Fraction_Water_Mean == R_UNDEF) MODIS_Cloud_Fraction_Water_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Fraction_Ice_Mean == R_UNDEF) MODIS_Cloud_Fraction_Ice_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Fraction_High_Mean == R_UNDEF) MODIS_Cloud_Fraction_High_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Fraction_Mid_Mean == R_UNDEF) MODIS_Cloud_Fraction_Mid_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Fraction_Low_Mean == R_UNDEF) MODIS_Cloud_Fraction_Low_Mean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Total_Mean == R_UNDEF) MODIS_Optical_Thickness_Total_Mean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Water_Mean == R_UNDEF) MODIS_Optical_Thickness_Water_Mean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Ice_Mean == R_UNDEF) MODIS_Optical_Thickness_Ice_Mean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Total_LogMean == R_UNDEF) MODIS_Optical_Thickness_Total_LogMean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Water_LogMean == R_UNDEF) MODIS_Optical_Thickness_Water_LogMean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_Ice_LogMean == R_UNDEF) MODIS_Optical_Thickness_Ice_LogMean = MAPL_UNDEF
            where (MODIS_Cloud_Particle_Size_Water_Mean == R_UNDEF) MODIS_Cloud_Particle_Size_Water_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Particle_Size_Ice_Mean == R_UNDEF) MODIS_Cloud_Particle_Size_Ice_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Top_Pressure_Total_Mean == R_UNDEF) MODIS_Cloud_Top_Pressure_Total_Mean = MAPL_UNDEF
            where (MODIS_Cloud_Top_Pressure_Total_Mean <= 0.0) MODIS_Cloud_Top_Pressure_Total_Mean = MAPL_UNDEF
            where (MODIS_Liquid_Water_Path_Mean == R_UNDEF) MODIS_Liquid_Water_Path_Mean = MAPL_UNDEF
            where (MODIS_Ice_Water_Path_Mean == R_UNDEF) MODIS_Ice_Water_Path_Mean = MAPL_UNDEF
            where (MODIS_Optical_Thickness_vs_Cloud_Top_Pressure == R_UNDEF) &
                 MODIS_Optical_Thickness_vs_Cloud_Top_Pressure = MAPL_UNDEF
         end if

         if (use_satsim_lidar + use_satsim > 0) then
            where (lidar_cfad_sr == R_UNDEF) lidar_cfad_sr = MAPL_UNDEF
            where (lidar_lidarcld > 1.0) lidar_lidarcld = MAPL_UNDEF
            where (lidar_lidarcld < 0.0) lidar_lidarcld = MAPL_UNDEF
            where (lidar_cldlayer == R_UNDEF) lidar_cldlayer = MAPL_UNDEF
            where (lidar_parasolrefl == R_UNDEF) lidar_parasolrefl = MAPL_UNDEF
         end if

         if (use_satsim_radar + use_satsim > 0) then
            where (radar_ze_tot == R_UNDEF) radar_ze_tot = MAPL_UNDEF
            where (radar_lidar_only_freq_cloud == R_UNDEF) radar_lidar_only_freq_cloud = MAPL_UNDEF
            where (radar_lidar_tcc == R_UNDEF) radar_lidar_tcc = MAPL_UNDEF
            where (radar_cfad_ze == R_UNDEF) radar_cfad_ze = MAPL_UNDEF
         end if

         if (use_satsim_misr + use_satsim > 0) then
            where (MISR_meanztop == R_UNDEF) MISR_meanztop = MAPL_UNDEF
            where (MISR_meanztop <= 0.0) MISR_meanztop = MAPL_UNDEF
            where (fq_MISR == R_UNDEF) fq_MISR = MAPL_UNDEF
            where (MISR_cldarea == R_UNDEF) MISR_cldarea = MAPL_UNDEF
            where (MISR_dist_model_layertops == R_UNDEF) MISR_dist_model_layertops = MAPL_UNDEF
         end if
#endif

         ! ISCCP exports

         ! 4 Cumulus (CU) subcategories
         !    fq_isccp3D(2:3,6:7)

         if (associated(ISCCP_CU_OA)) then
            ISCCP_CU_OA = fq_isccp3D(:, :, 2, 6)
         end if

         if (associated(ISCCP_CU_OB)) then
            ISCCP_CU_OB = fq_isccp3D(:, :, 3, 6)
         end if

         if (associated(ISCCP_CU_UA)) then
            ISCCP_CU_UA = fq_isccp3D(:, :, 2, 7)
         end if

         if (associated(ISCCP_CU_UB)) then
            ISCCP_CU_UB = fq_isccp3D(:, :, 3, 7)
         end if

         ! 4 Stratocumulus STCU subcategories
         !    ISCCP_isccp3D(4:5,6:7)

         if (associated(ISCCP_STCU_OA)) then
            ISCCP_STCU_OA = fq_isccp3D(:, :, 4, 6)
         end if

         if (associated(ISCCP_STCU_OB)) then
            ISCCP_STCU_OB = fq_isccp3D(:, :, 5, 6)
         end if

         if (associated(ISCCP_STCU_UA)) then
            ISCCP_STCU_UA = fq_isccp3D(:, :, 4, 7)
         end if

         if (associated(ISCCP_STCU_UB)) then
            ISCCP_STCU_UB = fq_isccp3D(:, :, 5, 7)
         end if

         ! 4 Stratus ST subcategories
         !    fq_isccp3D(6:7,6:7)

         if (associated(ISCCP_ST_OA)) then
            ISCCP_ST_OA = fq_isccp3D(:, :, 6, 6)
         end if

         if (associated(ISCCP_ST_OB)) then
            ISCCP_ST_OB = fq_isccp3D(:, :, 7, 6)
         end if

         if (associated(ISCCP_ST_UA)) then
            ISCCP_ST_UA = fq_isccp3D(:, :, 6, 7)
         end if

         if (associated(ISCCP_ST_UB)) then
            ISCCP_ST_UB = fq_isccp3D(:, :, 7, 7)
         end if

         ! 4 Altocumulus ACU subcategories
         !    fq_isccp3D(2:3,4:5)

         if (associated(ISCCP_ACU_OA)) then
            ISCCP_ACU_OA = fq_isccp3D(:, :, 2, 4)
         end if

         if (associated(ISCCP_ACU_OB)) then
            ISCCP_ACU_OB = fq_isccp3D(:, :, 3, 4)
         end if

         if (associated(ISCCP_ACU_UA)) then
            ISCCP_ACU_UA = fq_isccp3D(:, :, 2, 5)
         end if

         if (associated(ISCCP_ACU_UB)) then
            ISCCP_ACU_UB = fq_isccp3D(:, :, 3, 5)
         end if

         ! 4 Altostratus AST subcategories
         !    fq_isccp3D(4:5,4:5)

         if (associated(ISCCP_AST_OA)) then
            ISCCP_AST_OA = fq_isccp3D(:, :, 4, 4)
         end if

         if (associated(ISCCP_AST_OB)) then
            ISCCP_AST_OB = fq_isccp3D(:, :, 5, 4)
         end if

         if (associated(ISCCP_AST_UA)) then
            ISCCP_AST_UA = fq_isccp3D(:, :, 4, 5)
         end if

         if (associated(ISCCP_AST_UB)) then
            ISCCP_AST_UB = fq_isccp3D(:, :, 5, 5)
         end if

         ! 4 Nimbostratus NST subcategories
         !    fq_isccp3D(6:7,4:5)

         if (associated(ISCCP_NST_OA)) then
            ISCCP_NST_OA = fq_isccp3D(:, :, 6, 4)
         end if

         if (associated(ISCCP_NST_OB)) then
            ISCCP_NST_OB = fq_isccp3D(:, :, 7, 4)
         end if

         if (associated(ISCCP_NST_UA)) then
            ISCCP_NST_UA = fq_isccp3D(:, :, 6, 5)
         end if

         if (associated(ISCCP_NST_UB)) then
            ISCCP_NST_UB = fq_isccp3D(:, :, 7, 5)
         end if

         ! 6 Cirrus CI subcategories
         !    fq_isccp3D(2:3,1:3)

         if (associated(ISCCP_CI_OA)) then
            ISCCP_CI_OA = fq_isccp3D(:, :, 2, 1)
         end if

         if (associated(ISCCP_CI_OB)) then
            ISCCP_CI_OB = fq_isccp3D(:, :, 3, 1)
         end if

         if (associated(ISCCP_CI_MA)) then
            ISCCP_CI_MA = fq_isccp3D(:, :, 2, 2)
         end if

         if (associated(ISCCP_CI_MB)) then
            ISCCP_CI_MB = fq_isccp3D(:, :, 3, 2)
         end if

         if (associated(ISCCP_CI_UA)) then
            ISCCP_CI_UA = fq_isccp3D(:, :, 2, 3)
         end if

         if (associated(ISCCP_CI_UB)) then
            ISCCP_CI_UB = fq_isccp3D(:, :, 3, 3)
         end if

         ! 6 Cirrostratus CIST subcategories
         !    fq_isccp3D(4:5,1:3)

         if (associated(ISCCP_CIST_OA)) then
            ISCCP_CIST_OA = fq_isccp3D(:, :, 4, 1)
         end if

         if (associated(ISCCP_CIST_OB)) then
            ISCCP_CIST_OB = fq_isccp3D(:, :, 5, 1)
         end if

         if (associated(ISCCP_CIST_MA)) then
            ISCCP_CIST_MA = fq_isccp3D(:, :, 4, 2)
         end if

         if (associated(ISCCP_CIST_MB)) then
            ISCCP_CIST_MB = fq_isccp3D(:, :, 5, 2)
         end if

         if (associated(ISCCP_CIST_UA)) then
            ISCCP_CIST_UA = fq_isccp3D(:, :, 4, 3)
         end if

         if (associated(ISCCP_CIST_UB)) then
            ISCCP_CIST_UB = fq_isccp3D(:, :, 5, 3)
         end if

         ! 6 Cumulonimbus CB subcategories
         !    fq_isccp3D(6:7,1:3)

         if (associated(ISCCP_CB_OA)) then
            ISCCP_CB_OA = fq_isccp3D(:, :, 6, 1)
         end if

         if (associated(ISCCP_CB_OB)) then
            ISCCP_CB_OB = fq_isccp3D(:, :, 7, 1)
         end if

         if (associated(ISCCP_CB_MA)) then
            ISCCP_CB_MA = fq_isccp3D(:, :, 6, 2)
         end if

         if (associated(ISCCP_CB_MB)) then
            ISCCP_CB_MB = fq_isccp3D(:, :, 7, 2)
         end if

         if (associated(ISCCP_CB_UA)) then
            ISCCP_CB_UA = fq_isccp3D(:, :, 6, 3)
         end if

         if (associated(ISCCP_CB_UB)) then
            ISCCP_CB_UB = fq_isccp3D(:, :, 7, 3)
         end if

         ! 7 Subvisible/Subdetection (SUBV) subcategories
         !    ISCCP_isccp3D(1,1:7)

         if (associated(ISCCP_SUBV1)) then
            ISCCP_SUBV1 = fq_isccp3D(:, :, 1, 1)
         end if

         if (associated(ISCCP_SUBV2)) then
            ISCCP_SUBV2 = fq_isccp3D(:, :, 1, 2)
         end if

         if (associated(ISCCP_SUBV3)) then
            ISCCP_SUBV3 = fq_isccp3D(:, :, 1, 3)
         end if

         if (associated(ISCCP_SUBV4)) then
            ISCCP_SUBV4 = fq_isccp3D(:, :, 1, 4)
         end if

         if (associated(ISCCP_SUBV5)) then
            ISCCP_SUBV5 = fq_isccp3D(:, :, 1, 5)
         end if

         if (associated(ISCCP_SUBV6)) then
            ISCCP_SUBV6 = fq_isccp3D(:, :, 1, 6)
         end if

         if (associated(ISCCP_SUBV7)) then
            ISCCP_SUBV7 = fq_isccp3D(:, :, 1, 7)
         end if

         ! 7 pressure levels of all thicknesses
         !    ISCCP_isccp3D(:,:,:,1:7)

         if (associated(CLISCCP1)) then
            CLISCCP1 = fq_isccp3D(:, :, :, 1)
         end if

         if (associated(CLISCCP2)) then
            CLISCCP2 = fq_isccp3D(:, :, :, 2)
         end if

         if (associated(CLISCCP3)) then
            CLISCCP3 = fq_isccp3D(:, :, :, 3)
         end if

         if (associated(CLISCCP4)) then
            CLISCCP4 = fq_isccp3D(:, :, :, 4)
         end if

         if (associated(CLISCCP5)) then
            CLISCCP5 = fq_isccp3D(:, :, :, 5)
         end if

         if (associated(CLISCCP6)) then
            CLISCCP6 = fq_isccp3D(:, :, :, 6)
         end if

         if (associated(CLISCCP7)) then
            CLISCCP7 = fq_isccp3D(:, :, :, 7)
         end if

         if (associated(ISCCP1)) then
            ISCCP1 = fq_isccp3D(:, :, :, 1)
         end if

         if (associated(ISCCP2)) then
            ISCCP2 = fq_isccp3D(:, :, :, 2)
         end if

         if (associated(ISCCP3)) then
            ISCCP3 = fq_isccp3D(:, :, :, 3)
         end if

         if (associated(ISCCP4)) then
            ISCCP4 = fq_isccp3D(:, :, :, 4)
         end if

         if (associated(ISCCP5)) then
            ISCCP5 = fq_isccp3D(:, :, :, 5)
         end if

         if (associated(ISCCP6)) then
            ISCCP6 = fq_isccp3D(:, :, :, 6)
         end if

         if (associated(ISCCP7)) then
            ISCCP7 = fq_isccp3D(:, :, :, 7)
         end if

         if (associated(CLTISCCP)) then
            CLTISCCP = reshape(ISCCP_totalcldarea, (/ IM, JM /))
         end if

         if (associated(TCLISCCP)) then
            TCLISCCP = reshape(ISCCP_totalcldarea, (/ IM, JM /))
         end if

         if (associated(PCTISCCP)) then
            PCTISCCP = reshape(ISCCP_meanptop, (/ IM, JM /))
         end if

         if (associated(CTPISCCP)) then
            CTPISCCP = reshape(ISCCP_meanptop, (/ IM, JM /))
         end if

         if (associated(ALBISCCP)) then
            ALBISCCP = reshape(ISCCP_meanalbedocld, (/ IM, JM /))
         end if

         if (associated(TBISCCP)) then
            TBISCCP = reshape(ISCCP_meanallskybrighttemp, (/ IM, JM /))
         end if

         ! CALIPSO/lidar exports

         if (associated(CLCALIPSO)) then
            CLCALIPSO = reshape(lidar_lidarcld(:, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLLCALIPSO)) then
            CLLCALIPSO = reshape(lidar_cldlayer(:, 1), (/IM, JM /)) ! low
         end if

         if (associated(CLMCALIPSO)) then
            CLMCALIPSO = reshape(lidar_cldlayer(:, 2), (/IM, JM /)) ! middle
         end if

         if (associated(CLHCALIPSO)) then
            CLHCALIPSO = reshape(lidar_cldlayer(:, 3), (/IM, JM /)) ! high
         end if

         if (associated(CLTCALIPSO)) then
            CLTCALIPSO = reshape(lidar_cldlayer(:, 4), (/IM, JM /)) ! total
         end if

         if (associated(PARASOLREFL0)) then
            PARASOLREFL0 = reshape(lidar_parasolrefl, (/IM, JM, PARASOL_NREFL /))
         end if

         if (associated(PARASOLREFL1)) then
            PARASOLREFL1 = reshape(lidar_parasolrefl(:, 1), (/IM, JM /))
         end if

         if (associated(PARASOLREFL2)) then
            PARASOLREFL2 = reshape(lidar_parasolrefl(:, 2), (/IM, JM /))
         end if

         if (associated(PARASOLREFL3)) then
            PARASOLREFL3 = reshape(lidar_parasolrefl(:, 3), (/IM, JM /))
         end if

         if (associated(PARASOLREFL4)) then
            PARASOLREFL4 = reshape(lidar_parasolrefl(:, 4), (/IM, JM /))
         end if

         if (associated(PARASOLREFL5)) then
            PARASOLREFL5 = reshape(lidar_parasolrefl(:, 5), (/IM, JM /))
         end if

         if (associated(CFADLIDARSR532_01)) then
            CFADLIDARSR532_01 = reshape(lidar_cfad_sr(:, 1, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_02)) then
            CFADLIDARSR532_02 = reshape(lidar_cfad_sr(:, 2, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_03)) then
            CFADLIDARSR532_03 = reshape(lidar_cfad_sr(:, 3, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_04)) then
            CFADLIDARSR532_04 = reshape(lidar_cfad_sr(:, 4, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_05)) then
            CFADLIDARSR532_05 = reshape(lidar_cfad_sr(:, 5, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_06)) then
            CFADLIDARSR532_06 = reshape(lidar_cfad_sr(:, 6, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_07)) then
            CFADLIDARSR532_07 = reshape(lidar_cfad_sr(:, 7, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_08)) then
            CFADLIDARSR532_08 = reshape(lidar_cfad_sr(:, 8, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_09)) then
            CFADLIDARSR532_09 = reshape(lidar_cfad_sr(:, 9, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_10)) then
            CFADLIDARSR532_10 = reshape(lidar_cfad_sr(:, 10, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_11)) then
            CFADLIDARSR532_11 = reshape(lidar_cfad_sr(:, 11, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_12)) then
            CFADLIDARSR532_12 = reshape(lidar_cfad_sr(:, 12, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_13)) then
            CFADLIDARSR532_13 = reshape(lidar_cfad_sr(:, 13, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_14)) then
            CFADLIDARSR532_14 = reshape(lidar_cfad_sr(:, 14, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CFADLIDARSR532_15)) then
            CFADLIDARSR532_15 = reshape(lidar_cfad_sr(:, 15, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(LIDARPMOL)) then
            LIDARPMOL = reshape(lidar_pmol(:, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(LIDARPTOT)) then
            LIDARPTOT = reshape(sum(lidar_beta_tot(:, :, LM:1:-1), 2) / (1. * ncolumns), (/IM, JM, LM /))
         end if

         if (associated(LIDARTAUTOT)) then
            LIDARTAUTOT = reshape(sum(lidar_tau_tot(:, :, LM:1:-1), 2) / (1. * ncolumns), (/IM, JM, LM /))
         end if

         ! CLOUDSAT/radar exports

#define SATSIMTEMP
#ifdef SATSIMTEMP
         if (associated(RADARZETOT)) then
            radar_ze_tot_mask = (radar_ze_tot /= MAPL_UNDEF) ! mask out undefined columns
            ncvalid = count(radar_ze_tot_mask, dim=2) ! number of defined columns
            radar_ze_tot_max = maxval(radar_ze_tot, dim=2, mask=radar_ze_tot_mask) ! maximum among columns
            radar_ze_tot_tmp = spread(radar_ze_tot_max, dim=2, ncopies=ncolumns) ! max copied to all columns
            where (radar_ze_tot_mask) &
                 radar_ze_tot_tmp = 10.0**((radar_ze_tot - radar_ze_tot_tmp) / 10.0) ! convert to rel reflectivity
            where (ncvalid > 0)
               radar_ze_tot_mean = &
                    sum(radar_ze_tot_tmp, dim=2, mask=radar_ze_tot_mask) / real(ncvalid) ! mean rel reflectivity
               radar_ze_tot_mean = radar_ze_tot_max + 10.0 * log10(radar_ze_tot_mean) ! convert back to dBZ
               elsewhere
               radar_ze_tot_mean = MAPL_UNDEF
            end where
            RADARZETOT = reshape(radar_ze_tot_mean(:, LM:1:-1), (/IM, JM, LM/))
         end if
#else
         if (associated(RADARZETOT)) then
            RADARZETOT = reshape(sum(radar_ze_tot(:, :, LM:1:-1), 2) / (1. * ncolumns), (/IM, JM, LM /))
         end if
#endif ! SATSIMTEMP

         if (associated(RADARLTCC)) then
            RADARLTCC = reshape(radar_lidar_tcc, (/IM, JM /))
         end if

         if (associated(CLCALIPSO2)) then
            CLCALIPSO2 = reshape(radar_lidar_only_freq_cloud(:, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD01)) then
            CLOUDSATCFAD01 = reshape(radar_cfad_ze(:, 1, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD02)) then
            CLOUDSATCFAD02 = reshape(radar_cfad_ze(:, 2, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD03)) then
            CLOUDSATCFAD03 = reshape(radar_cfad_ze(:, 3, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD04)) then
            CLOUDSATCFAD04 = reshape(radar_cfad_ze(:, 4, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD05)) then
            CLOUDSATCFAD05 = reshape(radar_cfad_ze(:, 5, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD06)) then
            CLOUDSATCFAD06 = reshape(radar_cfad_ze(:, 6, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD07)) then
            CLOUDSATCFAD07 = reshape(radar_cfad_ze(:, 7, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD08)) then
            CLOUDSATCFAD08 = reshape(radar_cfad_ze(:, 8, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD09)) then
            CLOUDSATCFAD09 = reshape(radar_cfad_ze(:, 9, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD10)) then
            CLOUDSATCFAD10 = reshape(radar_cfad_ze(:, 10, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD11)) then
            CLOUDSATCFAD11 = reshape(radar_cfad_ze(:, 11, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD12)) then
            CLOUDSATCFAD12 = reshape(radar_cfad_ze(:, 12, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD13)) then
            CLOUDSATCFAD13 = reshape(radar_cfad_ze(:, 13, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD14)) then
            CLOUDSATCFAD14 = reshape(radar_cfad_ze(:, 14, LM:1:-1), (/IM, JM, LM /))
         end if

         if (associated(CLOUDSATCFAD15)) then
            CLOUDSATCFAD15 = reshape(radar_cfad_ze(:, 15, LM:1:-1), (/IM, JM, LM /))
         end if

         ! MODIS exports -- currently available only from COSP

         if (associated(MDSCLDFRCTTL)) then
            MDSCLDFRCTTL = reshape(MODIS_Cloud_Fraction_Total_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDFRCWTR)) then
            MDSCLDFRCWTR = reshape(MODIS_Cloud_Fraction_Water_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDFRCH2O)) then
            MDSCLDFRCH2O = reshape(MODIS_Cloud_Fraction_Water_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDFRCICE)) then
            MDSCLDFRCICE = reshape(MODIS_Cloud_Fraction_Ice_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDFRCHI)) then
            MDSCLDFRCHI = reshape(MODIS_Cloud_Fraction_High_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDFRCMID)) then
            MDSCLDFRCMID = reshape(MODIS_Cloud_Fraction_Mid_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDFRCLO)) then
            MDSCLDFRCLO = reshape(MODIS_Cloud_Fraction_Low_Mean, (/IM, JM /))
         end if

         if (associated(MDSOPTHCKTTL)) then
            MDSOPTHCKTTL = reshape(MODIS_Optical_Thickness_Total_Mean, (/IM, JM /))
         end if

         if (associated(MDSOPTHCKWTR)) then
            MDSOPTHCKWTR = reshape(MODIS_Optical_Thickness_Water_Mean, (/IM, JM /))
         end if

         if (associated(MDSOPTHCKH2O)) then
            MDSOPTHCKH2O = reshape(MODIS_Optical_Thickness_Water_Mean, (/IM, JM /))
         end if

         if (associated(MDSOPTHCKICE)) then
            MDSOPTHCKICE = reshape(MODIS_Optical_Thickness_Ice_Mean, (/IM, JM /))
         end if

         if (associated(MDSOPTHCKTTLLG)) then
            MDSOPTHCKTTLLG = reshape(MODIS_Optical_Thickness_Total_LogMean, (/IM, JM /))
         end if

         if (associated(MDSOPTHCKWTRLG)) then
            MDSOPTHCKWTRLG = reshape(MODIS_Optical_Thickness_Water_LogMean, (/IM, JM /))
         end if

         if (associated(MDSOPTHCKH2OLG)) then
            MDSOPTHCKH2OLG = reshape(MODIS_Optical_Thickness_Water_LogMean, (/IM, JM /))
         end if

         if (associated(MDSOPTHCKICELG)) then
            MDSOPTHCKICELG = reshape(MODIS_Optical_Thickness_Ice_LogMean, (/IM, JM /))
         end if

         if (associated(MDSCLDSZWTR)) then
            MDSCLDSZWTR = reshape(MODIS_Cloud_Particle_Size_Water_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDSZH20)) then
            MDSCLDSZH20 = reshape(MODIS_Cloud_Particle_Size_Water_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDSZICE)) then
            MDSCLDSZICE = reshape(MODIS_Cloud_Particle_Size_Ice_Mean, (/IM, JM /))
         end if

         if (associated(MDSCLDTOPPS)) then
            MDSCLDTOPPS = reshape(MODIS_Cloud_Top_Pressure_Total_Mean, (/IM, JM /))
         end if

         if (associated(MDSWTRPATH)) then
            MDSWTRPATH = reshape(MODIS_Liquid_Water_Path_Mean, (/IM, JM /))
         end if

         if (associated(MDSH2OPATH)) then
            MDSH2OPATH = reshape(MODIS_Liquid_Water_Path_Mean, (/IM, JM /))
         end if

         if (associated(MDSICEPATH)) then
            MDSICEPATH = reshape(MODIS_Ice_Water_Path_Mean, (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST11)) then
            MDSTAUPRSHIST11 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 1, 1), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST12)) then
            MDSTAUPRSHIST12 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 1, 2), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST13)) then
            MDSTAUPRSHIST13 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 1, 3), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST14)) then
            MDSTAUPRSHIST14 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 1, 4), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST15)) then
            MDSTAUPRSHIST15 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 1, 5), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST16)) then
            MDSTAUPRSHIST16 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 1, 6), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST17)) then
            MDSTAUPRSHIST17 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 1, 7), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST21)) then
            MDSTAUPRSHIST21 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 2, 1), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST22)) then
            MDSTAUPRSHIST22 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 2, 2), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST23)) then
            MDSTAUPRSHIST23 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 2, 3), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST24)) then
            MDSTAUPRSHIST24 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 2, 4), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST25)) then
            MDSTAUPRSHIST25 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 2, 5), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST26)) then
            MDSTAUPRSHIST26 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 2, 6), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST27)) then
            MDSTAUPRSHIST27 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 2, 7), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST31)) then
            MDSTAUPRSHIST31 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 3, 1), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST32)) then
            MDSTAUPRSHIST32 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 3, 2), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST33)) then
            MDSTAUPRSHIST33 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 3, 3), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST34)) then
            MDSTAUPRSHIST34 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 3, 4), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST35)) then
            MDSTAUPRSHIST35 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 3, 5), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST36)) then
            MDSTAUPRSHIST36 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 3, 6), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST37)) then
            MDSTAUPRSHIST37 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 3, 7), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST41)) then
            MDSTAUPRSHIST41 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 4, 1), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST42)) then
            MDSTAUPRSHIST42 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 4, 2), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST43)) then
            MDSTAUPRSHIST43 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 4, 3), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST44)) then
            MDSTAUPRSHIST44 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 4, 4), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST45)) then
            MDSTAUPRSHIST45 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 4, 5), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST46)) then
            MDSTAUPRSHIST46 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 4, 6), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST47)) then
            MDSTAUPRSHIST47 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 4, 7), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST51)) then
            MDSTAUPRSHIST51 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 5, 1), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST52)) then
            MDSTAUPRSHIST52 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 5, 2), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST53)) then
            MDSTAUPRSHIST53 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 5, 3), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST54)) then
            MDSTAUPRSHIST54 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 5, 4), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST55)) then
            MDSTAUPRSHIST55 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 5, 5), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST56)) then
            MDSTAUPRSHIST56 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 5, 6), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST57)) then
            MDSTAUPRSHIST57 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 5, 7), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST61)) then
            MDSTAUPRSHIST61 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 6, 1), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST62)) then
            MDSTAUPRSHIST62 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 6, 2), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST63)) then
            MDSTAUPRSHIST63 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 6, 3), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST64)) then
            MDSTAUPRSHIST64 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 6, 4), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST65)) then
            MDSTAUPRSHIST65 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 6, 5), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST66)) then
            MDSTAUPRSHIST66 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 6, 6), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST67)) then
            MDSTAUPRSHIST67 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 6, 7), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST71)) then
            MDSTAUPRSHIST71 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 7, 1), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST72)) then
            MDSTAUPRSHIST72 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 7, 2), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST73)) then
            MDSTAUPRSHIST73 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 7, 3), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST74)) then
            MDSTAUPRSHIST74 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 7, 4), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST75)) then
            MDSTAUPRSHIST75 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 7, 5), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST76)) then
            MDSTAUPRSHIST76 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 7, 6), (/IM, JM /))
         end if

         if (associated(MDSTAUPRSHIST77)) then
            MDSTAUPRSHIST77 = reshape(MODIS_Optical_Thickness_vs_Cloud_Top_Pressure(:, 7, 7), (/IM, JM /))
         end if

         if (associated(MISRMNCLDTP)) then
            MISRMNCLDTP = reshape(MISR_meanztop, (/IM, JM /))
         end if

         if (associated(MISRCLDAREA)) then
            MISRCLDAREA = reshape(MISR_cldarea, (/IM, JM /))
         end if

         if (associated(MISRLYRTP0)) then
            MISRLYRTP0 = reshape(MISR_dist_model_layertops(:, 1), (/IM, JM /))
         end if

         if (associated(MISRLYRTP250)) then
            MISRLYRTP250 = reshape(MISR_dist_model_layertops(:, 2), (/IM, JM /))
         end if

         if (associated(MISRLYRTP750)) then
            MISRLYRTP750 = reshape(MISR_dist_model_layertops(:, 3), (/IM, JM /))
         end if

         if (associated(MISRLYRTP1250)) then
            MISRLYRTP1250 = reshape(MISR_dist_model_layertops(:, 4), (/IM, JM /))
         end if

         if (associated(MISRLYRTP1750)) then
            MISRLYRTP1750 = reshape(MISR_dist_model_layertops(:, 5), (/IM, JM /))
         end if

         if (associated(MISRLYRTP2250)) then
            MISRLYRTP2250 = reshape(MISR_dist_model_layertops(:, 6), (/IM, JM /))
         end if

         if (associated(MISRLYRTP2750)) then
            MISRLYRTP2750 = reshape(MISR_dist_model_layertops(:, 7), (/IM, JM /))
         end if

         if (associated(MISRLYRTP3500)) then
            MISRLYRTP3500 = reshape(MISR_dist_model_layertops(:, 8), (/IM, JM /))
         end if

         if (associated(MISRLYRTP4500)) then
            MISRLYRTP4500 = reshape(MISR_dist_model_layertops(:, 9), (/IM, JM /))
         end if

         if (associated(MISRLYRTP6000)) then
            MISRLYRTP6000 = reshape(MISR_dist_model_layertops(:, 10), (/IM, JM /))
         end if

         if (associated(MISRLYRTP8000)) then
            MISRLYRTP8000 = reshape(MISR_dist_model_layertops(:, 11), (/IM, JM /))
         end if

         if (associated(MISRLYRTP10000)) then
            MISRLYRTP10000 = reshape(MISR_dist_model_layertops(:, 12), (/IM, JM /))
         end if

         if (associated(MISRLYRTP12000)) then
            MISRLYRTP12000 = reshape(MISR_dist_model_layertops(:, 13), (/IM, JM /))
         end if

         if (associated(MISRLYRTP14000)) then
            MISRLYRTP14000 = reshape(MISR_dist_model_layertops(:, 14), (/IM, JM /))
         end if

         if (associated(MISRLYRTP16000)) then
            MISRLYRTP16000 = reshape(MISR_dist_model_layertops(:, 15), (/IM, JM /))
         end if

         if (associated(MISRLYRTP18000)) then
            MISRLYRTP18000 = reshape(MISR_dist_model_layertops(:, 16), (/IM, JM /))
         end if

         if (associated(MISRFQ0)) then
            MISRFQ0 = reshape(fq_MISR(:, :, 1), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ250)) then
            MISRFQ250 = reshape(fq_MISR(:, :, 2), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ750)) then
            MISRFQ750 = reshape(fq_MISR(:, :, 3), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ1250)) then
            MISRFQ1250 = reshape(fq_MISR(:, :, 4), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ1750)) then
            MISRFQ1750 = reshape(fq_MISR(:, :, 5), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ2250)) then
            MISRFQ2250 = reshape(fq_MISR(:, :, 6), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ2750)) then
            MISRFQ2750 = reshape(fq_MISR(:, :, 7), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ3500)) then
            MISRFQ3500 = reshape(fq_MISR(:, :, 8), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ4500)) then
            MISRFQ4500 = reshape(fq_MISR(:, :, 9), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ6000)) then
            MISRFQ6000 = reshape(fq_MISR(:, :, 10), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ8000)) then
            MISRFQ8000 = reshape(fq_MISR(:, :, 11), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ10000)) then
            MISRFQ10000 = reshape(fq_MISR(:, :, 12), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ12000)) then
            MISRFQ12000 = reshape(fq_MISR(:, :, 13), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ14000)) then
            MISRFQ14000 = reshape(fq_MISR(:, :, 14), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ16000)) then
            MISRFQ16000 = reshape(fq_MISR(:, :, 15), (/IM, JM, 7 /))
         end if

         if (associated(MISRFQ18000)) then
            MISRFQ18000 = reshape(fq_MISR(:, :, 16), (/IM, JM, 7 /))
         end if

         _GET_NAMED_PRIVATE_STATE(gc, SatSim_State, PRIVATE_STATE, self)

         if (self%nmask_vars > 0) then
            ! get orb bundle
            call ESMF_StateGet(import, 'SATORB', bundle, _RC)
            ! TODO (step 4): the masked-export machinery still goes through the
            ! MAPL2 generic state to introspect the registered export specs.
            call MAPL_GetObjectFromGC(gc, STATE, _RC)
            call MAPL_Get(STATE, ExportSpec=ExportSpec, _RC)
            do i = 1, self%nmask_vars
               vindex = MAPL_VarSpecGetIndex(ExportSpec, self%export_name(i), _RC)
               call MAPL_VarSpecGet(ExportSpec(vindex), DIMS=mapl_dims, ungridded_dims=ungridded_dims, _RC)
               ! mask from bundle
               call MAPL_FieldBundleGetPointer(bundle, trim(self%mask_name(i)), ptr_mask, _RC)
               if (self%newvar(i)) then

                  ! determine what dimension pointer we need
                  if (mapl_dims == MAPL_DimsHorzOnly .and. (.not. associated(ungridded_dims))) then
                     call MAPL_GetPointer(export, ptr2d_new, self%newvar_name(i), _RC)
                     if (associated(ptr2d_new)) then
                        call MAPL_GetPointer(export, ptr2d, self%export_name(i), _RC)
                        ptr2d_new = ptr2d
                        where (ptr_mask == MAPL_UNDEF)
                           ptr2d_new = MAPL_UNDEF
                        end where
                        nullify(ptr2d_new)
                        nullify(ptr2d)
                     end if
                  end if
                  if (mapl_dims == MAPL_DimsHorzOnly .and. associated(ungridded_dims)) then
                     call MAPL_GetPointer(export, ptr3d_new, self%newvar_name(i), _RC)
                     if (associated(ptr3d_new)) then
                        call MAPL_GetPointer(export, ptr3d, self%export_name(i), _RC)
                        ptr3d_new = ptr3d
                        do j = 1, ungridded_dims(1)
                           where (ptr_mask == MAPL_UNDEF)
                              ptr3d_new(:, :, j) = MAPL_UNDEF
                           end where
                        end do
                        nullify(ptr3d_new)
                        nullify(ptr3d)
                     end if
                  end if
                  if (mapl_dims == MAPL_DimsHorzVert) then
                     call MAPL_GetPointer(export, ptr3d_new, self%newvar_name(i), _RC)
                     if (associated(ptr3d_new)) then
                        call MAPL_GetPointer(export, ptr3d, self%export_name(i), _RC)
                        ptr3d_new = ptr3d
                        do j = 1, LM
                           where (ptr_mask == MAPL_UNDEF)
                              ptr3d_new(:, :, j) = MAPL_UNDEF
                           end where
                        end do
                        nullify(ptr3d_new)
                        nullify(ptr3d)
                     end if
                  end if

               else
                  ! determine what dimension pointer we need
                  if (mapl_dims == MAPL_DimsHorzOnly .and. (.not. associated(ungridded_dims))) then
                     call MAPL_GetPointer(export, ptr2d, self%newvar_name(i), _RC)
                     if (associated(ptr2d)) then
                        where (ptr_mask == MAPL_UNDEF)
                           ptr2d = MAPL_UNDEF
                        end where
                        nullify(ptr2d)
                     end if
                  end if
                  if (mapl_dims == MAPL_DimsHorzOnly .and. associated(ungridded_dims)) then
                     call MAPL_GetPointer(export, ptr3d, self%newvar_name(i), _RC)
                     if (associated(ptr3d)) then
                        do j = 1, ungridded_dims(1)
                           where (ptr_mask == MAPL_UNDEF)
                              ptr3d(:, :, j) = MAPL_UNDEF
                           end where
                        end do
                        nullify(ptr3d)
                     end if
                  end if
                  if (mapl_dims == MAPL_DimsHorzVert) then
                     call MAPL_GetPointer(export, ptr3d, self%newvar_name(i), _RC)
                     if (associated(ptr3d)) then
                        do j = 1, LM
                           where (ptr_mask == MAPL_UNDEF)
                              ptr3d(:, :, j) = MAPL_UNDEF
                           end where
                        end do
                        nullify(ptr3d)
                     end if
                  end if

               end if

               nullify(ptr_mask)

            end do
         end if

         ! deallocate stuff
         deallocate(frac_out, _STAT)
         deallocate(lidar_beta_tot, _STAT)
         deallocate(lidar_tau_tot, _STAT)
         deallocate(radar_ze_tot, _STAT)
         deallocate(radar_ze_tot_tmp, _STAT)
         deallocate(radar_ze_tot_mask, _STAT)

         call FREE_COSP_GRIDBOX(gbx)
         call FREE_COSP_SUBGRID(sgx)
         if (cfg%Lisccp_sim) call FREE_COSP_ISCCP(isccp)
         if (cfg%Lradar_sim) call FREE_COSP_SGRADAR(sgradar)
         if (cfg%Llidar_sim) call FREE_COSP_SGLIDAR(sglidar)
         call FREE_COSP_VGRID(vgrid)
         if (cfg%Llidar_sim) call FREE_COSP_LIDARSTATS(stlidar)
         if (cfg%Lradar_sim) call FREE_COSP_RADARSTATS(stradar)
         if (cfg%Lmodis_sim) call FREE_COSP_MODIS(modis)
         if (cfg%Lmisr_sim) call FREE_COSP_MISR(misr)

         _RETURN(_SUCCESS)

      end subroutine SIM_DRIVER

   end subroutine Run

end module GEOS_SatsimGridCompMod
